enterprise_data_pipeline:
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_DBT_USER_DEV', env_var('SNOWFLAKE_DBT_USER', 'DEV_DBT_USER')) }}"
      password: "{{ env_var('SNOWFLAKE_DBT_PASSWORD', env_var('SNOWFLAKE_PASSWORD', '')) }}"
      private_key: "{{ '' if env_var('SNOWFLAKE_DBT_PRIVATE_KEY_PATH_DEV', env_var('SNOWFLAKE_DBT_PRIVATE_KEY_PATH', '')) else env_var('SNOWFLAKE_DBT_PRIVATE_KEY_DEV', env_var('SNOWFLAKE_DBT_PRIVATE_KEY', env_var('DEV_DBT_USER_RSA_PRIVATE_KEY', ''))) }}"
      private_key_path: "{{ env_var('SNOWFLAKE_DBT_PRIVATE_KEY_PATH_DEV', env_var('SNOWFLAKE_DBT_PRIVATE_KEY_PATH', '')) }}"
      private_key_passphrase: "{{ env_var('SNOWFLAKE_DBT_PRIVATE_KEY_PASSPHRASE', '') }}"
      role: "{{ env_var('SNOWFLAKE_DBT_ROLE_DEV', env_var('SNOWFLAKE_DBT_ROLE', 'DEV_DBT_ROLE')) }}"
      warehouse: "{{ env_var('SNOWFLAKE_DBT_WAREHOUSE_DEV', env_var('SNOWFLAKE_DBT_WAREHOUSE', 'DEV_DBT_WH')) }}"
      database: "{{ env_var('SNOWFLAKE_SILVER_DATABASE_DEV', env_var('SNOWFLAKE_SILVER_DATABASE', 'DEV_SILVER_DB')) }}"
      schema: "{{ env_var('SNOWFLAKE_SILVER_SCHEMA', 'CLEANSED') }}"
      threads: 1
    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_DBT_USER_PROD', env_var('SNOWFLAKE_DBT_USER', 'PROD_DBT_USER')) }}"
      password: "{{ env_var('SNOWFLAKE_DBT_PASSWORD', env_var('SNOWFLAKE_PASSWORD', '')) }}"
      private_key: "{{ '' if env_var('SNOWFLAKE_DBT_PRIVATE_KEY_PATH_PROD', env_var('SNOWFLAKE_DBT_PRIVATE_KEY_PATH', '')) else env_var('SNOWFLAKE_DBT_PRIVATE_KEY_PROD', env_var('SNOWFLAKE_DBT_PRIVATE_KEY', env_var('PROD_DBT_USER_RSA_PRIVATE_KEY', ''))) }}"
      private_key_path: "{{ env_var('SNOWFLAKE_DBT_PRIVATE_KEY_PATH_PROD', env_var('SNOWFLAKE_DBT_PRIVATE_KEY_PATH', '')) }}"
      private_key_passphrase: "{{ env_var('SNOWFLAKE_DBT_PRIVATE_KEY_PASSPHRASE', '') }}"
      role: "{{ env_var('SNOWFLAKE_DBT_ROLE_PROD', env_var('SNOWFLAKE_DBT_ROLE', 'PROD_DBT_ROLE')) }}"
      warehouse: "{{ env_var('SNOWFLAKE_DBT_WAREHOUSE_PROD', env_var('SNOWFLAKE_DBT_WAREHOUSE', 'PROD_DBT_WH')) }}"
      database: "{{ env_var('SNOWFLAKE_SILVER_DATABASE_PROD', env_var('SNOWFLAKE_SILVER_DATABASE', 'PROD_SILVER_DB')) }}"
      schema: "{{ env_var('SNOWFLAKE_SILVER_SCHEMA', 'CLEANSED') }}"
      threads: 1
  target: "{{ env_var('APP_ENV', 'dev') }}"