-- =====================================================
-- Description: Snowflake Infrastructure Setup for Terraform (DEV)
-- Target: Development Environment
-- Author: Project Admin
-- =====================================================

-- 1. Terraform execution role/user
-- -----------------------------------------------------
CREATE ROLE IF NOT EXISTS DEV_TF_ADMIN_ROLE;

CREATE USER IF NOT EXISTS DEV_TFRUNNER_USER
  RSA_PUBLIC_KEY='<YOUR_DEV_RSA_PUBLIC_KEY_HERE>'
  DEFAULT_ROLE=DEV_TF_ADMIN_ROLE;

GRANT ROLE DEV_TF_ADMIN_ROLE TO USER DEV_TFRUNNER_USER;

-- Grant privileges required for Terraform automation
GRANT CREATE DATABASE, CREATE WAREHOUSE, CREATE ROLE, CREATE USER, MANAGE GRANTS
  ON ACCOUNT TO ROLE DEV_TF_ADMIN_ROLE;

-- Grant to SYSADMIN for governance/visibility
GRANT ROLE DEV_TF_ADMIN_ROLE TO ROLE SYSADMIN;

-- 2. Data layer databases/schemas
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS DEV_BRONZE_DB;
CREATE SCHEMA   IF NOT EXISTS DEV_BRONZE_DB.RAW_DATA;

CREATE DATABASE IF NOT EXISTS DEV_SILVER_DB;
CREATE SCHEMA   IF NOT EXISTS DEV_SILVER_DB.CLEANSED;

CREATE DATABASE IF NOT EXISTS DEV_GOLD_DB;
CREATE SCHEMA   IF NOT EXISTS DEV_GOLD_DB.MARKETING_MART;

-- 3. Transfer DB ownership to DEV_TF_ADMIN_ROLE
-- -----------------------------------------------------
GRANT OWNERSHIP ON DATABASE DEV_BRONZE_DB TO ROLE DEV_TF_ADMIN_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE DEV_SILVER_DB TO ROLE DEV_TF_ADMIN_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE DEV_GOLD_DB TO ROLE DEV_TF_ADMIN_ROLE COPY CURRENT GRANTS;

-- 3.1 Transfer schema ownership to DEV_TF_ADMIN_ROLE
-- -----------------------------------------------------
GRANT OWNERSHIP ON SCHEMA DEV_BRONZE_DB.RAW_DATA TO ROLE DEV_TF_ADMIN_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA DEV_SILVER_DB.CLEANSED TO ROLE DEV_TF_ADMIN_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA DEV_GOLD_DB.MARKETING_MART TO ROLE DEV_TF_ADMIN_ROLE COPY CURRENT GRANTS;
