-- =====================================================
-- Description: Snowflake Infrastructure Setup for Terraform (PROD)
-- Target: Production Environment
-- Author: Project Admin
-- =====================================================

-- 1. Terraform execution role/user
-- -----------------------------------------------------
CREATE ROLE IF NOT EXISTS PROD_TF_ADMIN_ROLE;

CREATE USER IF NOT EXISTS PROD_TFRUNNER_USER
  RSA_PUBLIC_KEY='<YOUR_PROD_RSA_PUBLIC_KEY_HERE>'
  DEFAULT_ROLE=PROD_TF_ADMIN_ROLE;

GRANT ROLE PROD_TF_ADMIN_ROLE TO USER PROD_TFRUNNER_USER;

-- Grant privileges required for Terraform automation
GRANT CREATE DATABASE, CREATE WAREHOUSE, CREATE ROLE, CREATE USER, MANAGE GRANTS
  ON ACCOUNT TO ROLE PROD_TF_ADMIN_ROLE;

-- Grant to SYSADMIN for governance/visibility
GRANT ROLE PROD_TF_ADMIN_ROLE TO ROLE SYSADMIN;

-- 2. Data layer databases/schemas
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS PROD_BRONZE_DB;
CREATE SCHEMA   IF NOT EXISTS PROD_BRONZE_DB.RAW_DATA;

CREATE DATABASE IF NOT EXISTS PROD_SILVER_DB;
CREATE SCHEMA   IF NOT EXISTS PROD_SILVER_DB.CLEANSED;

CREATE DATABASE IF NOT EXISTS PROD_GOLD_DB;
CREATE SCHEMA   IF NOT EXISTS PROD_GOLD_DB.MARKETING_MART;

-- 3. Transfer DB ownership to PROD_TF_ADMIN_ROLE
-- -----------------------------------------------------
GRANT OWNERSHIP ON DATABASE PROD_BRONZE_DB TO ROLE PROD_TF_ADMIN_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE PROD_SILVER_DB TO ROLE PROD_TF_ADMIN_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE PROD_GOLD_DB TO ROLE PROD_TF_ADMIN_ROLE COPY CURRENT GRANTS;

-- 3.1 Transfer schema ownership to PROD_TF_ADMIN_ROLE
-- -----------------------------------------------------
GRANT OWNERSHIP ON SCHEMA PROD_BRONZE_DB.RAW_DATA TO ROLE PROD_TF_ADMIN_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA PROD_SILVER_DB.CLEANSED TO ROLE PROD_TF_ADMIN_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA PROD_GOLD_DB.MARKETING_MART TO ROLE PROD_TF_ADMIN_ROLE COPY CURRENT GRANTS;
