-- =====================================================
-- Description: Snowflake Infrastructure Setup for Terraform (DEV)
-- Target: Development Environment
-- Author: Project Admin
-- =====================================================

USE ROLE ACCOUNTADMIN;

-- =====================================================
-- Required runtime inputs (replace placeholders before execution)
-- =====================================================
SET EXPECTED_ACCOUNT            = '<DEV_ACCOUNT_IDENTIFIER>'; -- ex: ORG-DEV_ACCOUNT
SET RUNNER_RSA_PUBLIC_KEY       = '<YOUR_DEV_RSA_PUBLIC_KEY_HERE>';
SET RUNNER_RSA_PUBLIC_KEY_2     = ''; -- optional: set only during key rotation
SET HCP_TERRAFORM_CIDR_1        = '<HCP_TERRAFORM_CIDR_1>';
SET CORPORATE_CIDR_1            = '<CORPORATE_CIDR_1>';

-- =====================================================
-- Preflight checks
-- =====================================================
EXECUTE IMMEDIATE $$
DECLARE
  expected_account STRING := $EXPECTED_ACCOUNT;
  pubkey_1 STRING := $RUNNER_RSA_PUBLIC_KEY;
  pubkey_2 STRING := $RUNNER_RSA_PUBLIC_KEY_2;
  hcp_cidr_1 STRING := $HCP_TERRAFORM_CIDR_1;
  corp_cidr_1 STRING := $CORPORATE_CIDR_1;
BEGIN
  IF UPPER(CURRENT_ROLE()) <> 'ACCOUNTADMIN' THEN
    RAISE STATEMENT_ERROR WITH MESSAGE => 'Bootstrap must be executed as ACCOUNTADMIN.';
  END IF;

  IF expected_account LIKE '<%>' THEN
    RAISE STATEMENT_ERROR WITH MESSAGE => 'Replace EXPECTED_ACCOUNT placeholder before execution.';
  END IF;

  IF UPPER(CURRENT_ACCOUNT()) <> UPPER(expected_account) THEN
    RAISE STATEMENT_ERROR WITH MESSAGE => 'Account mismatch. Stop to avoid cross-environment execution.';
  END IF;

  IF TRIM(pubkey_1) = '' OR pubkey_1 LIKE '<%>' THEN
    RAISE STATEMENT_ERROR WITH MESSAGE => 'Replace RUNNER_RSA_PUBLIC_KEY before execution.';
  END IF;

  IF TRIM(pubkey_2) != '' AND pubkey_2 LIKE '<%>' THEN
    RAISE STATEMENT_ERROR WITH MESSAGE => 'Replace RUNNER_RSA_PUBLIC_KEY_2 before execution or leave it empty.';
  END IF;

  IF hcp_cidr_1 LIKE '<%>' OR corp_cidr_1 LIKE '<%>' THEN
    RAISE STATEMENT_ERROR WITH MESSAGE => 'Replace network policy CIDR placeholders before execution.';
  END IF;
END;
$$;

-- 1. Terraform execution role/user
-- -----------------------------------------------------
CREATE ROLE IF NOT EXISTS DEV_TF_ADMIN_ROLE;

CREATE USER IF NOT EXISTS DEV_TFRUNNER_USER
  RSA_PUBLIC_KEY=$RUNNER_RSA_PUBLIC_KEY
  DEFAULT_ROLE=DEV_TF_ADMIN_ROLE;

ALTER USER DEV_TFRUNNER_USER SET
  RSA_PUBLIC_KEY=$RUNNER_RSA_PUBLIC_KEY,
  DEFAULT_ROLE=DEV_TF_ADMIN_ROLE;

EXECUTE IMMEDIATE $$
DECLARE
  pubkey_2 STRING := $RUNNER_RSA_PUBLIC_KEY_2;
BEGIN
  IF TRIM(pubkey_2) = '' THEN
    EXECUTE IMMEDIATE 'ALTER USER DEV_TFRUNNER_USER UNSET RSA_PUBLIC_KEY_2';
  ELSE
    EXECUTE IMMEDIATE 'ALTER USER DEV_TFRUNNER_USER SET RSA_PUBLIC_KEY_2 = ''' || REPLACE(pubkey_2, '''', '''''') || '''';
  END IF;
END;
$$;

GRANT ROLE DEV_TF_ADMIN_ROLE TO USER DEV_TFRUNNER_USER;

-- Grant privileges required for Terraform automation
GRANT CREATE DATABASE, CREATE WAREHOUSE, CREATE ROLE, CREATE USER, MANAGE GRANTS
  ON ACCOUNT TO ROLE DEV_TF_ADMIN_ROLE;

-- Grant to SYSADMIN for governance/visibility
GRANT ROLE DEV_TF_ADMIN_ROLE TO ROLE SYSADMIN;

-- 2. Data layer databases/schemas
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS DEV_BRONZE_DB;
ALTER DATABASE DEV_BRONZE_DB SET DATA_RETENTION_TIME_IN_DAYS = 7;
CREATE SCHEMA   IF NOT EXISTS DEV_BRONZE_DB.RAW_DATA WITH MANAGED ACCESS;
ALTER SCHEMA DEV_BRONZE_DB.RAW_DATA ENABLE MANAGED ACCESS;

CREATE DATABASE IF NOT EXISTS DEV_SILVER_DB;
ALTER DATABASE DEV_SILVER_DB SET DATA_RETENTION_TIME_IN_DAYS = 7;
CREATE SCHEMA   IF NOT EXISTS DEV_SILVER_DB.CLEANSED WITH MANAGED ACCESS;
ALTER SCHEMA DEV_SILVER_DB.CLEANSED ENABLE MANAGED ACCESS;

CREATE DATABASE IF NOT EXISTS DEV_GOLD_DB;
ALTER DATABASE DEV_GOLD_DB SET DATA_RETENTION_TIME_IN_DAYS = 7;
CREATE SCHEMA   IF NOT EXISTS DEV_GOLD_DB.MARKETING_MART WITH MANAGED ACCESS;
ALTER SCHEMA DEV_GOLD_DB.MARKETING_MART ENABLE MANAGED ACCESS;

-- 2.1 Network policy for Terraform execution
-- -----------------------------------------------------
CREATE NETWORK POLICY IF NOT EXISTS DEV_TERRAFORM_NETWORK_POLICY
  ALLOWED_IP_LIST = ($HCP_TERRAFORM_CIDR_1, $CORPORATE_CIDR_1);

ALTER NETWORK POLICY DEV_TERRAFORM_NETWORK_POLICY
  SET ALLOWED_IP_LIST = ($HCP_TERRAFORM_CIDR_1, $CORPORATE_CIDR_1);

ALTER USER DEV_TFRUNNER_USER SET NETWORK_POLICY = DEV_TERRAFORM_NETWORK_POLICY;

-- 3. Transfer DB ownership to DEV_TF_ADMIN_ROLE
-- -----------------------------------------------------
GRANT OWNERSHIP ON DATABASE DEV_BRONZE_DB TO ROLE DEV_TF_ADMIN_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE DEV_SILVER_DB TO ROLE DEV_TF_ADMIN_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE DEV_GOLD_DB TO ROLE DEV_TF_ADMIN_ROLE COPY CURRENT GRANTS;

-- 3.1 Transfer schema ownership to DEV_TF_ADMIN_ROLE
-- -----------------------------------------------------
GRANT OWNERSHIP ON SCHEMA DEV_BRONZE_DB.RAW_DATA TO ROLE DEV_TF_ADMIN_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA DEV_SILVER_DB.CLEANSED TO ROLE DEV_TF_ADMIN_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA DEV_GOLD_DB.MARKETING_MART TO ROLE DEV_TF_ADMIN_ROLE COPY CURRENT GRANTS;

-- 3.2 Transfer network policy ownership to DEV_TF_ADMIN_ROLE
-- -----------------------------------------------------
GRANT OWNERSHIP ON NETWORK POLICY DEV_TERRAFORM_NETWORK_POLICY TO ROLE DEV_TF_ADMIN_ROLE COPY CURRENT GRANTS;
